development:
  sessions:
    default:
      database: bhf-demo-mongoid
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      max_retries_on_connection_failure: 20
      persist_in_safe_mode: true
      skip_version_check: true
